# Generated by Django 4.1.7 on 2023-03-29 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_member_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='passwords',
            field=models.IntegerField(null=True),
        ),
    ]
