# Generated by Django 4.1.7 on 2023-03-29 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_member_passwords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='passwords',
        ),
        migrations.AlterField(
            model_name='member',
            name='password',
            field=models.IntegerField(null=True),
        ),
    ]
