# Generated by Django 4.1.7 on 2023-03-29 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_member_passwords_alter_member_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='username',
            new_name='user',
        ),
    ]
