# Generated by Django 4.1.7 on 2023-03-29 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_username_member_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='user',
            new_name='username',
        ),
    ]
